name: canarinho_again_app
description: Canarinho Again.
publish_to: "none"
version: 1.1.0+1

environment:
  sdk: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.0.3
  json_annotation: ^4.6.0
  build_runner: ^2.1.11
  http: ^0.13.4
  http_interceptor: ^1.0.2
  reactive_forms: ^14.1.0
  reactive_date_time_picker: ^0.6.1
  reactive_dropdown_search: ^0.12.0
  toggle_switch: ^2.0.1
  badges: ^3.1.1
  get_it: ^7.2.0
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
